default_language_version:
    python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-merge-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - "--max-complexity=50"

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.1
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
